name: unidata-standard
channels:
  - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  - jupyterlab
  # User requested packages
  - metpy
  - siphon
  - xarray
  - netcdf4
  - cartopy
  - shapely
  - scikit-learn
  - tropycal
